### ISSUE TITLE
Flexibility of the Bounty Mod

### ISSUE THREAD

**Issue by Grambosch** [WalkerInTheVoid/WurmMods#2]
Hello , 
im playing on a Server with Deedupkeep and we have a Mod running giving us once a month a silver for a requested item, 
This is enough for keeping up a deed but if you play with others on one bigger deed you get problems if people leave. (long intro i´ll come to the point now )
I suggested your Bounty mod and the admins tried it out and debatted over it and in the end 
it wasnt taken for not being as adjustable as desired.
Would it be possible to make bountys adjustable for servers in:
Bounty value per Animal
Max Bounty per Period (eg max 1 SIlver a month per player)
With the current settings your mod would make our Silver for an item Dealer worthless and it should be just an option to raise your income a little.
I hope i wrote clear enough for you
Thanks in advance

**Comment by WalkerInTheVoid** [comment]
Hi there!

First off, thanks for your interest.  Other people using these mods are why I published them and update :)

I'm slightly confused about your feature change request, as the BountyMod already offers configuration items to change the bounty value per critter in the .properties file, along with a just flat multiplier if you want to apply some divisor across the board.  (the latter is just for ease of use, if you want to cut all bounties by a half for example, that way you change ONE thing instead of several dozen)

Max Bounty Per period...hmm.  That would be a lot harder, though no such thing as impossible I suppose.  If nothing else it'd most likely be possible to have bounties pay out from the same "pool" as selling random items with the "Sell" command (and thus ~3 copper per hour max).

As far as the second item goes, bear in mind as things currently stand it should be possible to lower a creature's bounty all the way to 1 iron if you're so inclined, though admittedly I have not personally tested that (something I will have to change) with regards to player-bred animals (which, if experience gain for player-bred animals is on, default to 1/10th the bounty of a wild animal of the same type, as I wanted the hunter to have greater income than the rancher who gets to control the battlefield so to speak.)

Please let me know if I can further assist

**Comment by Grambosch** [comment]
The config options in the propertiest were sufficient enough.
I think the Admins didnt realize they were there.
Thanks a lot
